spring:
  datasource:
    url: jdbc:mariadb://donkey-rds.cnohqzdklodx.ap-northeast-2.rds.amazonaws.com:3306/project
    username: nana
    password: nana1234
    driverClassName: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /resources/templates

mybatis:
  mapper-locations:
    - classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

SECRET_KEY : "DEV1A4C28485C32709A0D888EDD62DEE89D9A5D3"